package com.otienochris.procurement_management_system.services;

import com.otienochris.procurement_management_system.Dtos.RFIDto;
import com.otienochris.procurement_management_system.mappers.RFIMapper;
import com.otienochris.procurement_management_system.models.Document;
import com.otienochris.procurement_management_system.models.RFI;
import com.otienochris.procurement_management_system.repositories.RFIRepo;
import com.otienochris.procurement_management_system.responses.RFIResponse;
import lombok.RequiredArgsConstructor;
import org.springframework.stereotype.Service;
import org.springframework.util.StringUtils;
import org.springframework.web.servlet.support.ServletUriComponentsBuilder;

import java.util.*;

@Service
@RequiredArgsConstructor
public class RFIService {

    private final RFIRepo rfiRepo;
    private final RFIMapper rfiMapper;


    public List<RFIResponse> getAll(){
        List<RFIResponse> responses = new ArrayList<>();
        rfiRepo.findAll().forEach(rfi -> {
            responses.add(createResponse(rfi));
        });
        return responses;
    }

    public RFIResponse getById(Integer id){

        RFI rfi = rfiRepo.findById(id).orElseThrow(() -> {
            throw new NoSuchElementException("The RFI with Id: " + id + " does not exist!");
        });
        return createResponse(rfi);
    }

    public RFIResponse saveRFI(RFIDto rfiDto) {
        RFI rfi = rfiMapper.rfiDtoToRfi(rfiDto);
        rfi.getRfi().setType("RFI Document");
//        todo make it generated by the db
        RFI savedRfi = rfiRepo.save(rfi);
        return createResponse(savedRfi);
    }

    public void updateRFI(Integer id, RFIDto rfiDto){
        RFI newRFI = rfiMapper.rfiDtoToRfi(rfiDto);

        rfiRepo.findById(id).ifPresentOrElse(
                rfi -> {
                    rfi.setRfi(newRFI.getRfi());
                    rfi.setPurchaseOrderId(newRFI.getPurchaseOrderId());
                    rfi.setDescription(newRFI.getDescription());
                    rfi.getRfi().setType("RFI Document");
                    rfiRepo.save(rfi);

                },() -> {
                    throw new NoSuchElementException("Item with id: " + id + " not found");
                }
        );
    }

    public void delete(Integer id){
        rfiRepo.findById(id).ifPresentOrElse(
                rfiRepo::delete
                ,() -> { throw new NoSuchElementException("Item not found! "); });
    }


    public RFIResponse createResponse(RFI rfi) {
        Document rfiDocument = rfi.getRfi();

        String rfiName = StringUtils.cleanPath(rfiDocument.getFileName());

        String rfiDocumentPath = ServletUriComponentsBuilder.fromCurrentContextPath()
                .path("/api/v1/documents/download/")
                .path(rfiName)
                .toUriString();


        return RFIResponse.builder()
                .id(rfi.getId())
                .rfiUrl(rfiDocumentPath)
                .purchaseOrderId(rfi.getPurchaseOrderId())
                .description(rfi.getDescription())
                .dateCreated(rfi.getDateCreated())
                .build();
    }
}
