GET http://localhost:8080/api/item/all
Accept: application/json

###
POST http://localhost:8080/api/item/add
Content-Type: application/json

{
"description": "mattresses",
  "date": "2021-02-17",
  "expiry": "2022-02-18",
"quantity": "5",
"batchSerialNumber": "ADF445fg6"
}
###
POST http://localhost:8080/api/item/add
Content-Type: application/json

{
  "description": "shoes for lecturers",
  "date": "2021-02-16",
  "expiry": "2022-02-17",
  "quantity": "50",
  "batchSerialNumber": "ADF445fg4"
}
###
POST http://localhost:8080/api/item/add
Content-Type: application/json

{
  "description": "office tables",
  "date": "2021-01-16",
  "expiry": "2022-02-17",
  "quantity": "150",
  "batchSerialNumber": "ADF445fg2"
}


###
GET http://localhost:8080/api/item/get?id=1
Accept: application/json
###

POST http://localhost:8080/api/item/delete
Content-Type: application/json

{
  "itemId": 1,
  "description": "mattresses",
  "date": "2021-02-17",
  "expiry": "2022-02-18",
  "quantity": "5",
  "batchSerialNumber": "ADF445fg6"
}

###
#POST http://localhost:8080/api/item/update