GET http://localhost:8080/api/user/all
Accept: application/json

###
POST http://localhost:8080/api/user/add
Content-Type: application/json

{"firstName":"Otieno","lastName":"Chris", "password":"coo1","role": "admin", "email": "otienochris98@gmail.com"}

###
POST http://localhost:8080/api/user/add
Content-Type: application/json

{"firstName":"Otis","lastName":"Christ", "password":"coo2","role": "user", "email": "ohtischris@gmail.com"}

###
POST http://localhost:8080/api/user/add
Content-Type: application/json

{"firstName":"OT","lastName":"Christine", "password":"coo3","role": "admin", "email": "christopherotieno@gmail.com"}
###
GET http://localhost:8080/api/user/id/get?userId=1
Accept: application/json

###
GET http://localhost:8080/api/user/email/get?email=otienochris98@gmail.com
Accept: application/json

###
POST http://localhost:8080/api/user/delete/
Content-Type: application/json

{
  "userId": 3,
  "role": "admin",
  "email": "christopherotieno@gmail.com",
  "firstName": "OT",
  "lastName": "Christine",
  "password": "coo3",
  "clientId": "3"
}

###
POST http://localhost:8080/api/user/delete/get?id=1
Content-Type: application/json

###
POST http://localhost:8080/api/user/update
Content-Type: application/json

{
  "userId": 2,
  "role": "user",
  "email": "chrispine90@gmail.com",
  "firstName": "Oloo",
  "lastName": "Chrispine",
  "password": "twr2",
  "clientId": "2"
}